import { memo } from "react";
import { Ellipsis, Globe, LoaderCircle, Play, Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { resolveLucideIcon } from "@/lib/icon-utils";
import { useI18n } from "@/lib/i18n";
import type { AppRun, ProjectApp } from "@shared/types/project-apps";
import { appPhaseKey, isActiveRun } from "./app-utils";
export type AppCardAction = "open" | "details" | "edit" | "favorite" | "remove" | "stop" | "export";
interface Props { app: ProjectApp; run: AppRun | undefined; activeRunCount: number; projectName: string; spaceName: string; busy: boolean; onAction: (app: ProjectApp, action: AppCardAction) => void }
export const ProjectAppCard = memo(function ProjectAppCard({ app, run, activeRunCount, projectName, spaceName, busy, onAction }: Props) {
  const { t, language } = useI18n();
  const Icon = app.iconType === "lucide" ? resolveLucideIcon(app.icon) : null;
  const active = !!run && isActiveRun(run);
  const otherRuns = activeRunCount - Number(active);
  const failed = run?.phase === "failed";
  return <article className="flex h-full min-w-0 flex-col rounded-xl border bg-card p-4 shadow-sm transition-colors hover:border-primary/35">
    <div className="flex items-start gap-2"><button className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-muted text-2xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" onClick={() => onAction(app, "details")} aria-label={`${t("appsShowDetails")}: ${app.name}`}>{Icon ? <Icon className="size-6" /> : app.iconType === "emoji" ? app.icon : <Globe className="size-6" />}</button><div className="min-w-0 flex-1 pt-1"><button className="w-full truncate text-start text-sm font-semibold hover:underline" onClick={() => onAction(app, "details")}>{app.name}</button><p className="truncate text-xs text-muted-foreground">{projectName || t("appsWebsite")}{spaceName ? ` · ${spaceName}` : ""}</p></div><button className={`rounded p-1 hover:bg-accent ${app.favorite ? "text-amber-500" : "text-muted-foreground"}`} disabled={busy} onClick={() => onAction(app, "favorite")} aria-label={`${t(app.favorite ? "appsUnfavorite" : "appsFavorite")}: ${app.name}`} aria-pressed={app.favorite}><Star className="size-4" fill={app.favorite ? "currentColor" : "none"} /></button></div>
    <div className="mt-3 min-h-0 flex-1"><p className="flex items-center gap-1.5 text-xs"><span aria-hidden className={`size-1.5 rounded-full ${run?.phase === "failed" || run?.health === "unhealthy" ? "bg-destructive" : active ? "bg-emerald-500" : "bg-muted-foreground/40"}`} />{t(app.kind === "web" ? "appsWebsite" : appPhaseKey(run?.phase))}{run?.health === "ready" && active ? ` · ${t("appsReady")}` : ""}</p><p className="mt-1.5 truncate text-xs text-muted-foreground" title={app.kind === "web" ? app.url : app.workspace.rootPath}>{app.kind === "web" ? app.url : app.workspace.rootPath.split(/[\\/]/).slice(-2).join("/")}</p>{run?.error && <p className="mt-1 truncate text-xs text-destructive" title={run.error.message}>{run.error.message}</p>}{otherRuns > 0 && <p className="mt-1 text-[11px] text-emerald-600">{t("appsOtherRuns")}: {otherRuns}</p>}<p className="mt-1 truncate text-[11px] text-muted-foreground">{t("appsLastUsed")}: {app.lastUsedAt ? new Date(app.lastUsedAt).toLocaleString(language) : t("appsNeverUsed")}</p>{app.folder && <p className="mt-1 truncate text-[11px] text-muted-foreground">{app.folder}</p>}</div>
    <div className="mt-3 flex items-center gap-2"><Button size="sm" className="flex-1" variant={active || app.kind === "web" ? "secondary" : "default"} disabled={busy || run?.phase === "stopping"} onClick={() => onAction(app, failed ? "details" : "open")}>{busy || run?.phase === "starting" ? <LoaderCircle className="size-3.5 animate-spin" /> : <Play className="size-3.5" />}{t(failed ? "appsViewError" : app.kind === "web" || active ? "appsOpen" : "appsStartOpen")}</Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label={`${t("appsDetails")}: ${app.name}`}><Ellipsis className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => onAction(app, "details")}>{t("appsDetails")}</DropdownMenuItem><DropdownMenuItem onClick={() => onAction(app, "edit")}>{t("appsEdit")}</DropdownMenuItem>{activeRunCount > 0 && <DropdownMenuItem disabled={busy} onClick={() => onAction(app, "stop")}>{t("appsStop")}</DropdownMenuItem>}<DropdownMenuItem onClick={() => onAction(app, "export")}>{t("appsExport")}</DropdownMenuItem><DropdownMenuItem disabled={busy} onClick={() => onAction(app, "remove")} className="text-destructive">{t("appsRemove")}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
  </article>;
});
