/** Project Apps copy, consumed by the application's existing i18n provider. */
export const APPS_EN = {
  "Apps": "Apps", "Add to Apps": "Add to Apps", "Project is unavailable": "Project is unavailable",
  "New Tab": "New Tab", "Browser": "Browser", appsPreviewUnverified: "The process is running. This preview has not been verified by an HTTP health check.",
  "App context could not be inserted. Open Apps and try again.": "App context could not be inserted. Open Apps and try again.",
  appsOpenWebsite: "Open website", appsSaveWebsite: "Save as app", appsImproveHint: "A draft opens with the app context. Choose an agent in the composer before sending.",
  appsValidationAutoPort: "Automatic ports require the Vite or Next.js framework adapter.", appsManifestTooLarge: "The configuration file exceeds the 2 MB limit.",
  appsOtherRuns: "Other workspaces running", appsPermissionsTitle: "Agent requests an app action", appsPermissionsDescription: "Review the exact action below. Approval applies only to this request.",
  appsPermissionTool: "Tool", appsPermissionSession: "Chat", appsPermissionArguments: "Requested action and configuration", appsApproveOnce: "Approve once", appsDeny: "Deny",
  appsPermissionExpires: "Expires in", appsPermissionExpired: "This request has expired.", appsPermissionPending: "requests pending", appsPermissionLoading: "Checking pending requests…",
  appsViewError: "View error", appsLastUsed: "Last used", appsNeverUsed: "Not used yet", appsConfigRevision: "Configuration version", appsExitCode: "Exit code",
  appsOpenTerminal: "Open terminal here", appsTerminal: "Terminal", appsTerminalHint: "Use this terminal to inspect the selected directory or install missing dependencies. Closing it, leaving Details, or changing workspace ends these terminals.", appsTerminalFailed: "Unable to create a terminal.",
  appsPermissionBefore: "Previous configuration", appsPermissionAfter: "Requested configuration", appsPermissionChangedFields: "Changed fields",
  appsTitle: "Project Apps", appsSubtitle: "Run, preview and improve the apps in your projects.",
  appsAdd: "Add app", appsEdit: "Edit app", appsSearch: "Search apps, projects or URLs…", appsAllSpaces: "All spaces",
  appsAllProjects: "All projects", appsAllStates: "All states", appsAllFolders: "All folders", appsFavorites: "Favorites",
  appsAll: "All apps", appsSort: "Sort", appsRecent: "Recently used", appsName: "Name", appsManual: "Custom order",
  appsEmpty: "Your apps will live here", appsEmptyHint: "Add a project command or save a website to get started.",
  appsNoMatches: "No apps match these filters.", appsLoading: "Loading apps…", appsRefresh: "Refresh",
  appsImport: "Import configuration", appsExport: "Export configuration", appsClose: "Close", appsBack: "Back to apps",
  appsOpen: "Open", appsStartOpen: "Start and open", appsStart: "Start", appsStop: "Stop", appsRestart: "Restart",
  appsStarting: "Starting", appsRunning: "Running", appsStopping: "Stopping", appsStopped: "Stopped",
  appsFailed: "Failed", appsInterrupted: "Interrupted", appsReady: "Ready", appsChecking: "Checking", appsUnhealthy: "Unhealthy",
  appsUnknown: "Not checked", appsWebsite: "Website", appsManaged: "Project app", appsFavorite: "Favorite", appsUnfavorite: "Remove favorite",
  appsDetails: "Details", appsRemove: "Remove", appsRemoveTitle: "Remove this app?", appsRemoveHint: "All runs of this app will be stopped and its saved configuration and history removed. Project source files are kept.",
  appsCancel: "Cancel", appsSave: "Save", appsSaving: "Saving…", appsType: "App type", appsProject: "Project", appsSpace: "Space",
  appsWorkspace: "Workspace", appsWorkingDirectory: "Working directory (relative to workspace)", appsProjectRoot: "Project root",
  appsIcon: "Icon", appsFolder: "Folder", appsOrder: "Order", appsUrl: "Website URL", appsPreviewUrl: "Preview URL",
  appsPreviewHint: "Use {port} for the assigned port, for example http://127.0.0.1:{port}.", appsDiscover: "Detect commands",
  appsDiscovering: "Detecting…", appsCandidates: "Detected commands", appsNoCandidates: "No supported scripts found. Enter an executable and its arguments below.",
  appsCommandType: "Command type", appsPackageScript: "Package script", appsExecutable: "Executable", appsManager: "Package manager",
  appsScript: "Script name", appsArguments: "Arguments (one per line)", appsAdapter: "Framework", appsGeneric: "Generic",
  appsEnv: "Environment variables (NAME=value, one per line)", appsEnvHint: "Values are stored locally. Exports omit environment values.",
  appsPortMode: "Port policy", appsNoPort: "No managed port", appsFixedPort: "Fixed port", appsAutoPort: "Auto-assign port", appsPort: "Port / preferred port",
  appsReadiness: "Ready when", appsProcessReady: "Process is alive", appsHttpReady: "HTTP endpoint responds", appsHealthPath: "Health endpoint path",
  appsHttpStatuses: "Accepted HTTP statuses (comma separated)", appsTimeout: "Startup timeout (seconds)", appsAddProject: "Add project",
  appsValidationName: "Enter an app name.", appsValidationUrl: "Enter a valid http:// or https:// URL.",
  appsValidationWorkspace: "Select a project and workspace.", appsValidationCommand: "Enter a script or executable.",
  appsValidationPort: "Enter a port between 1 and 65535.", appsValidationEnv: "Each environment line must use NAME=value, without duplicate names.",
  appsValidationHealth: "Enter an absolute health path, valid HTTP statuses, and a timeout between 1 and 600 seconds.",
  appsValidationDirectory: "Use a relative directory inside the selected workspace.", appsError: "The operation failed.",
  appsRuntime: "Runtime", appsRunTarget: "Run in workspace", appsNoRuns: "No runs yet", appsRuns: "Runs", appsPreview: "Preview", appsLogs: "Logs",
  appsConfiguration: "Configuration", appsSessions: "Related chats", appsNoSessions: "No chats linked yet.", appsImprove: "Continue improving",
  appsIncludeLogs: "Include recent logs in the draft", appsNoPreview: "Start the app and wait until it is ready to preview it.",
  appsNoPreviewUrl: "No preview URL is configured. Open configuration to add one.", appsLogsEmpty: "No logs yet.", appsFollow: "Follow output",
  appsLogFilter: "Filter logs…", appsCopy: "Copy", appsCopied: "Copied", appsTruncated: "Earlier output was truncated.", appsSequenceGap: "Some output was lost. Reload logs to recover available output.",
  appsRunRevision: "Run uses an older configuration. Restart to apply saved changes.", appsCleanupPending: "Process cleanup is pending. Stop again before starting another run.",
  appsImportHint: "Import a Harnss app manifest. Managed apps are rebound to the selected local project. Review imported commands before starting them.",
  appsManifest: "Configuration JSON", appsChooseFile: "Choose JSON file", appsImportProject: "Target project for managed apps",
  appsImportSuccess: "Configuration imported", appsExportHint: "This manifest contains app configuration, with environment values removed. It does not contain project source code.",
  appsDownload: "Download JSON", appsImporting: "Importing…", appsSelectRun: "Select run", appsShowDetails: "Open app details",
  appsConfigConflict: "This configuration changed elsewhere. Refresh and try again.", appsMissingWorkspace: "The workspace is unavailable. Select a valid workspace in configuration.",
  appsRequestFailed: "Unable to reach the app service. Retry the operation.", appsNoProject: "Add a project to configure a local app.",
  appsNoLocalTarget: "Select a target project before importing managed apps.", appsLogPaused: "Automatic scrolling is paused.",
  appsWebImprove: "Website shortcuts have no local project to edit.", appsPreviewExternal: "Open in default browser", appsRunEnded: "This run has ended.",
} as const;

export const APPS_ZH: Record<keyof typeof APPS_EN, string> = {
  "Apps": "应用", "Add to Apps": "添加到应用", "Project is unavailable": "项目不可用",
  "New Tab": "新标签页", "Browser": "浏览器", appsPreviewUnverified: "进程正在运行，此预览尚未经 HTTP 健康检查验证。",
  "App context could not be inserted. Open Apps and try again.": "无法插入应用上下文，请打开应用面板后重试。",
  appsOpenWebsite: "打开网站", appsSaveWebsite: "保存为应用", appsImproveHint: "将打开包含应用上下文的草稿，发送前可在输入框选择 Agent。",
  appsValidationAutoPort: "自动端口需要选择 Vite 或 Next.js 框架适配器。", appsManifestTooLarge: "配置文件超过 2 MB 大小限制。",
  appsOtherRuns: "其他工作区运行中", appsPermissionsTitle: "Agent 请求操作应用", appsPermissionsDescription: "请检查下面的具体操作。批准仅适用于本次请求。",
  appsPermissionTool: "工具", appsPermissionSession: "会话", appsPermissionArguments: "请求操作与配置", appsApproveOnce: "仅批准一次", appsDeny: "拒绝",
  appsPermissionExpires: "剩余时间", appsPermissionExpired: "此请求已过期。", appsPermissionPending: "个请求待处理", appsPermissionLoading: "正在检查待处理请求…",
  appsViewError: "查看错误", appsLastUsed: "最近使用", appsNeverUsed: "尚未使用", appsConfigRevision: "配置版本", appsExitCode: "退出码",
  appsOpenTerminal: "在此目录打开终端", appsTerminal: "终端", appsTerminalHint: "可在此检查所选目录或安装缺失依赖。关闭终端、离开详情或更换工作区会结束这些终端。", appsTerminalFailed: "无法创建终端。",
  appsPermissionBefore: "原配置", appsPermissionAfter: "请求的新配置", appsPermissionChangedFields: "修改字段",
  appsTitle: "项目应用", appsSubtitle: "运行、预览并持续改进项目中的应用。", appsAdd: "添加应用", appsEdit: "编辑应用",
  appsSearch: "搜索应用、项目或网址…", appsAllSpaces: "全部空间", appsAllProjects: "全部项目", appsAllStates: "全部状态",
  appsAllFolders: "全部文件夹", appsFavorites: "收藏", appsAll: "全部应用", appsSort: "排序", appsRecent: "最近使用", appsName: "名称", appsManual: "自定义顺序",
  appsEmpty: "在这里管理你的应用", appsEmptyHint: "添加项目启动命令，或保存一个网站。", appsNoMatches: "没有符合筛选条件的应用。",
  appsLoading: "正在加载应用…", appsRefresh: "刷新", appsImport: "导入配置", appsExport: "导出配置", appsClose: "关闭", appsBack: "返回应用",
  appsOpen: "打开", appsStartOpen: "启动并打开", appsStart: "启动", appsStop: "停止", appsRestart: "重启", appsStarting: "正在启动",
  appsRunning: "运行中", appsStopping: "正在停止", appsStopped: "已停止", appsFailed: "启动失败", appsInterrupted: "已中断", appsReady: "就绪",
  appsChecking: "正在检查", appsUnhealthy: "健康检查失败", appsUnknown: "尚未检查", appsWebsite: "网站", appsManaged: "项目应用", appsFavorite: "收藏",
  appsUnfavorite: "取消收藏", appsDetails: "详情", appsRemove: "移除", appsRemoveTitle: "移除此应用？",
  appsRemoveHint: "将停止此应用的全部运行实例，并移除保存的配置与历史记录。项目源文件会保留。", appsCancel: "取消", appsSave: "保存", appsSaving: "正在保存…",
  appsType: "应用类型", appsProject: "项目", appsSpace: "空间", appsWorkspace: "工作区", appsWorkingDirectory: "工作目录（相对于工作区）", appsProjectRoot: "项目根目录",
  appsIcon: "图标", appsFolder: "文件夹", appsOrder: "顺序", appsUrl: "网站地址", appsPreviewUrl: "预览地址",
  appsPreviewHint: "使用 {port} 代表分配的端口，例如 http://127.0.0.1:{port}。", appsDiscover: "检测启动命令", appsDiscovering: "正在检测…",
  appsCandidates: "检测到的命令", appsNoCandidates: "没有找到支持的脚本，请手动填写可执行文件和参数。", appsCommandType: "命令类型",
  appsPackageScript: "包管理器脚本", appsExecutable: "可执行文件", appsManager: "包管理器", appsScript: "脚本名称", appsArguments: "参数（每行一个）",
  appsAdapter: "框架", appsGeneric: "通用", appsEnv: "环境变量（每行 NAME=value）", appsEnvHint: "值保存在本机，导出时不包含环境变量值。",
  appsPortMode: "端口策略", appsNoPort: "不管理端口", appsFixedPort: "固定端口", appsAutoPort: "自动分配端口", appsPort: "端口 / 首选端口",
  appsReadiness: "就绪条件", appsProcessReady: "进程存活", appsHttpReady: "HTTP 端点响应", appsHealthPath: "健康检查路径",
  appsHttpStatuses: "接受的 HTTP 状态码（逗号分隔）", appsTimeout: "启动超时（秒）", appsAddProject: "添加项目", appsValidationName: "请输入应用名称。",
  appsValidationUrl: "请输入有效的 http:// 或 https:// 地址。", appsValidationWorkspace: "请选择项目和工作区。", appsValidationCommand: "请输入脚本名或可执行文件。",
  appsValidationPort: "请输入 1 至 65535 之间的端口。", appsValidationEnv: "每行环境变量须为 NAME=value，名称不能重复。",
  appsValidationHealth: "请填写以 / 开头的健康检查路径、有效 HTTP 状态码，以及 1 至 600 秒的超时。",
  appsValidationDirectory: "请使用选定工作区内的相对目录。", appsError: "操作失败。", appsRuntime: "运行信息", appsRunTarget: "运行工作区",
  appsNoRuns: "尚无运行记录", appsRuns: "运行记录", appsPreview: "预览", appsLogs: "日志", appsConfiguration: "配置", appsSessions: "关联会话", appsNoSessions: "尚未关联会话。",
  appsImprove: "继续优化", appsIncludeLogs: "将最近日志附到草稿", appsNoPreview: "启动应用并等待就绪后即可预览。", appsNoPreviewUrl: "尚未配置预览地址，请在配置中添加。",
  appsLogsEmpty: "暂无日志。", appsFollow: "跟随输出", appsLogFilter: "筛选日志…", appsCopy: "复制", appsCopied: "已复制", appsTruncated: "更早的日志已被截断。",
  appsSequenceGap: "部分日志有缺失，重新加载可恢复仍可用的日志。", appsRunRevision: "此实例使用旧配置，重启后应用已保存的更改。",
  appsCleanupPending: "进程清理尚未完成，请再次停止后再启动。", appsImportHint: "导入 Harnss 应用配置清单。项目应用将绑定到所选本地项目，请检查导入的命令后再启动。",
  appsManifest: "配置 JSON", appsChooseFile: "选择 JSON 文件", appsImportProject: "项目应用的目标项目", appsImportSuccess: "配置已导入",
  appsExportHint: "此清单包含应用配置，环境变量值已移除，不包含项目源代码。", appsDownload: "下载 JSON", appsImporting: "正在导入…",
  appsSelectRun: "选择运行记录", appsShowDetails: "打开应用详情", appsConfigConflict: "配置已在其他位置更新，请刷新后重试。",
  appsMissingWorkspace: "工作区不可用，请在配置中选择有效工作区。", appsRequestFailed: "无法连接应用服务，请重试。", appsNoProject: "先添加一个项目，再配置本地应用。",
  appsNoLocalTarget: "导入项目应用前，请选择目标项目。", appsLogPaused: "已暂停自动滚动。", appsWebImprove: "网站快捷方式没有可编辑的本地项目。",
  appsPreviewExternal: "在默认浏览器打开", appsRunEnded: "此运行实例已结束。",
};
